CREATE TABLE MEMBER
(
    ID           VARCHAR2(20)    NOT NULL,
    PASSWORD1    VARCHAR2(20)    NOT NULL,
    PASSWORD2    VARCHAR2(20)    NOT NULL,
    NAME         VARCHAR2(10)    NOT NULL,
    BIRTHDAY     NUMBER(8)       NOT NULL,
    AREA1        VARCHAR2(20)    NOT NULL,
    AREA2        VARCHAR2(20)    NOT NULL,
    AREA3        VARCHAR2(20)    NOT NULL,
    EMAIL        VARCHAR2(20)    NOT NULL,
    PHONE        NUMBER(11)      NOT NULL,
    PRIMARY KEY (ID)
);


COMMENT ON TABLE MEMBER IS '회원정보';

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.PASSWORD1 IS '비밀번호';

COMMENT ON COLUMN MEMBER.PASSWORD2 IS '비밀번호확인';

COMMENT ON COLUMN MEMBER.NAME IS '이름';

COMMENT ON COLUMN MEMBER.BIRTHDAY IS '생년월일';

COMMENT ON COLUMN MEMBER.AREA1 IS '시/도';

COMMENT ON COLUMN MEMBER.AREA2 IS '시';

COMMENT ON COLUMN MEMBER.AREA3 IS '동/면/읍';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.PHONE IS '핸드폰번호';

--DROP TABLE MEMBER CASCADE CONSTRAINTS;

